### ISSUE TITLE
Hangs with largish? app

### ISSUE THREAD

**Issue by mordrax** [jinjor/elm-time-travel#7]
I love this project, or at least the idea of it, it's awesome!!! However, it doesn't work for me.

It seems to hang chrome everytime i pause and try to click on a previous state or into the 'Messages and diff'. I'm using TimeTravel.Navigation.program if that helps.

It could be the size of my model, i'm doing this on my game project ( https://github.com/mordrax/cotwelm )

**Comment by jinjor** [comment]
Thanks!

Which is most likely your case?
- run-time error
- response is too slow
- infinite loop

**Comment by mordrax** [comment]
It's hard to say between response is too slow and infinite loop because the
chrome tab just locks up and I don't get any response.

I'm able to see the new states but clicking on them does not bring up the
model unless it's the initial state 0.

**Comment by jinjor** [comment]
Can you give me the following log?

``` elm
_ = Debug.log (toString model) ""
```

I guess parsing is failed.

**Comment by mordrax** [comment]
Sorry, my model is quite big... actually it exceeded the 65536 char limit of the comment so I'm attaching as a file.
[model.txt](https://github.com/jinjor/elm-time-travel/files/343403/model.txt)

and again after changing some of the state:
[Uploading model2.txt…]()

**Comment by jinjor** [comment]
Thanks. Glad to see real-world usage.
I'll test using this data and try to improve performance.

**Comment by mordrax** [comment]
I introduced this project to another guy at a hacknight, we both loved it. His app is a crossword so the model is slightly smaller. He also noticed some lock-ups of his browser and the app getting progressively slower the more states that he accumulated.

States can accumulate quickly if we're tracking mouse movements or on Time.tick but yeah, looking forward to any potential fixes as it would mean a _huge_ help in not needing as much Debug.log statements and being able to step through state changes.

**Comment by jinjor** [comment]
I think there are two causes of this poor performance. One is the length of messages. The other is the largeness of the model. I suspect your case is caused by the latter.

Currently, this library has a needless parsing logic. It is like:

``` elm
str = toString model
ast = parse str
formattedStr = format ast
```

If we could see the internal structure of `model`, the heavy parsing is not needed at all. So I hope Elm will support the functionality for doing it someday. For now, I try to improve the performance or give you a good workaround.

**Comment by jinjor** [comment]
FYI, I just published new version(1.0.11). It's still very slow but much faster than previous version. (Your data (model.txt) is now parsed in 18s on my machine)

**Comment by mordrax** [comment]
Nice! Thanks for the quick response!

I just tried it out, deleted elm-stuff and started from scratch just to make sure however, I'm still getting the same behaviour, even after 1-2 minutes of waiting for a response. It seems the parser is still going... 

Here I try clicking on state `2: SplashMsg NewGame` and waited over a minute so far. (I'm running this on a 16gig macbook pro, i7 2.5ghz)
<img width="833" alt="screen shot 2016-07-02 at 10 29 28 am" src="https://cloud.githubusercontent.com/assets/4709169/16537193/296c32b6-4040-11e6-886b-bca7b644d19d.png">

**Comment by jinjor** [comment]
Looks like it needs more effort😞

**Comment by mordrax** [comment]
I tried looking at your Parser and AST... went wayyyy over my head. Not sure if I can help you much there. This is a promising project and the only one of it's kind so far in 0.17, so great effort and thank you for making it!

**Comment by jinjor** [comment]
Okay, just published 1.0.12.

Now your data is parsed in 3s on my PC, but not sure about other process (search, format, diff, render, etc). How do you feel this time?

**Comment by mordrax** [comment]
It's still hanging for me even with just a simple two state version... if you're taking 3s to parse and it hangs on mine, then it may not be the parsing but something else causing this issue...

<img width="590" alt="screen shot 2016-07-03 at 9 58 47 pm" src="https://cloud.githubusercontent.com/assets/4709169/16545289/60c93928-4169-11e6-83fe-a6c728080375.png">

I don't know if you have the time, but maybe you could try cloning and seeing for yourself the error?
https://github.com/mordrax/cotwelm (has install instructions, very simple to clone/run)

I'm going to try reducing the size of the model to see if this helps.

**Comment by jinjor** [comment]
I found diff is also very slow, but I'm still not sure what causes this slowness.

So I'll try to solve it, but if it takes long to solve it, I'll consider some workaround.

**Comment by mordrax** [comment]
Maybe, a possible workaround would be to disable diffing? I don't mind not having the diff. If I can see my states then that is already 100x better than manually putting in debug.log everywhere.

Unless you are only storing the diffs per state change and really require the diff, this is something that I can do myself.

**Comment by jinjor** [comment]
I just published 1.0.13.

Now "Messages and Diff" tab is not active by default, and diff is calculated lazily when it is in need.
Does this solve your problem?

**Comment by mordrax** [comment]
It is definitely better! I can use the model now and I think the lazy loading is what made it work. It takes about 5-6 secs to change state and then 1-3 secs to expand a record in the state. Slow but usable. 

However, my model is large and there is no scrollbar to see more than the screen height.
in your `detailView` function (https://github.com/jinjor/elm-time-travel/blob/1bdfb45711d20ca7ed72b7a1f23dc0961ae8edc5/src/TimeTravel/Internal/Styles.elm#L197), if you add `overflow-y: scroll` and `height: 90%`, it will add a scrollbar to the leftmost window. (For some reason, putting height at 100% goes off the screen)

**Comment by jinjor** [comment]
Just published 1.0.14. Now it has the scroll bar!

I close this issue because it's not "hanging" at least.
